# >>>>>>>>>>>>>>>>>>>>>>>>>
# 标题
title: 码农之路
# 简介
brief-intro: A Fun-driven Dev Engineer
# 邮箱
email: 591120280@qq.com
# 格言
description: 用舍由时，行藏在我
# 主页 the subpath of your site, e.g. /blog
baseurl: "" 
# 挂载于Github Page # the base hostname & protocol for your site, e.g. http://example.com
url: "https://XNRavenZen.github.io"
# Github 
github_username: XNRavenZen

# 图片存放位置
image_dir: /assets/image/
# css存放位置
css_dir: /assets/css/
# js存放位置
js_dir: /assets/js/
# 分类位置
category_dir: category/
# 标签位置
tag_dir: tag/

# markdown解析
markdown: kramdown

# 分页每页内容个数
paginate: 5
# 分页路径
paginate_path: "page:num"

plugins:
  # RSS功能插件
  - jekyll-feed
  # 分页插件
  - jekyll-paginate
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
# <<<<<<<<<<<<<<<<<<<<<<<<<